#
# Realm667 - An Awesome Awesomeness
# Copyright (C) 2015 Alexey Lysiuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

actors_all = (
# actors/chex/chexammo.txt
('MiniZorchRecharge'),
('MiniZorchPack'),
('LargeZorchRecharge'),
('LargeZorchPack'),
('PropulsorZorch'),
('PropulsorZorchPack'),
('PhasingZorch'),
('PhasingZorchPack'),
# actors/chex/chexdecorations.txt
('ChexCivilian1'),
('ChexCivilian2'),
('ChexCivilian3'),
('ChexLandingLight'),
('ChexSpaceship'),
('ChexAppleTree'),
('ChexBananaTree'),
('ChexOrangeTree'),
('ChexSubmergedPlant'),
('ChexTallFlower'),
('ChexTallFlower2'),
('ChexSlimeFountain'),
('ChexCavernColumn'),
('ChexCavernStalagmite'),
('ChexChemicalBurner'),
('ChexChemicalFlask'),
('ChexFlagOnPole'),
('ChexGasTank'),
('ChexLightColumn'),
('ChexMineCart'),
# actors/chex/chexitems.txt
('GlassOfWater'),
('BowlOfFruit'),
('BowlOfVegetables'),
('SuperchargeBreakfast'),
('SlimeRepellent'),
('ChexArmor'),
('SuperChexArmor'),
('ComputerAreaMap'),
('SlimeProofSuit'),
('Zorchpack'),
# actors/chex/chexkeys.txt
('ChexBlueCard'),
('ChexYellowCard'),
('ChexRedCard'),
# actors/chex/chexmonsters.txt
('FlemoidusCommonus'),
('FlemoidusBipedicus'),
('ArmoredFlemoidusBipedicus'),
('FlemoidusCycloptisCommonus'),
('Flembrane'),
('ChexSoul'),
# actors/chex/chexplayer.txt
('ChexPlayer'),
# actors/chex/chexweapons.txt
('Bootspoon'),
('SuperBootspork'),
('MiniZorcher'),
('LargeZorcher'),
('SuperLargeZorcher'),
('RapidZorcher'),
('ZorchPropulsor'),
('PropulsorMissile'),
('PhasingZorcher'),
('PhaseZorchMissile'),
('LAZDevice'),
('LAZBall'),
# actors/doom/arachnotron.txt
('Arachnotron'),
('ArachnotronPlasma'),
# actors/doom/archvile.txt
('Archvile'),
('ArchvileFire'),
# actors/doom/bossbrain.txt
('BossBrain'),
('BossEye'),
('BossTarget'),
('SpawnShot'),
('SpawnFire'),
# actors/doom/bruiser.txt
('BaronOfHell'),
('HellKnight'),
('BaronBall'),
# actors/doom/cacodemon.txt
('Cacodemon'),
('CacodemonBall'),
# actors/doom/cyberdemon.txt
('Cyberdemon'),
# actors/doom/deadthings.txt
('GibbedMarine'),
('GibbedMarineExtra'),
('DeadMarine'),
('DeadZombieMan'),
('DeadShotgunGuy'),
('DeadDoomImp'),
('DeadDemon'),
('DeadCacodemon'),
('DeadLostSoul'),
# actors/doom/demon.txt
('Demon'),
('Spectre'),
# actors/doom/doomammo.txt
('Clip'),
('ClipBox'),
('RocketAmmo'),
('RocketBox'),
('Cell'),
('CellPack'),
('Shell'),
('ShellBox'),
('Backpack'),
# actors/doom/doomarmor.txt
('ArmorBonus'),
('GreenArmor'),
('BlueArmor'),
# actors/doom/doomartifacts.txt
('InvulnerabilitySphere'),
('Soulsphere'),
('BlueArmorForMegasphere'),
('Megasphere'),
('BlurSphere'),
('RadSuit'),
('Infrared'),
('Allmap'),
('Berserk'),
# actors/doom/doomdecorations.txt
('TechLamp'),
('TechLamp2'),
('Column'),
('TallGreenColumn'),
('ShortGreenColumn'),
('TallRedColumn'),
('ShortRedColumn'),
('SkullColumn'),
('HeartColumn'),
('EvilEye'),
('FloatingSkull'),
('TorchTree'),
('BlueTorch'),
('GreenTorch'),
('RedTorch'),
('ShortBlueTorch'),
('ShortGreenTorch'),
('ShortRedTorch'),
('Stalagtite'),
('TechPillar'),
('Candlestick'),
('Candelabra'),
('BloodyTwitch'),
('Meat2'),
('Meat3'),
('Meat4'),
('Meat5'),
('NonsolidMeat2'),
('NonsolidMeat3'),
('NonsolidMeat4'),
('NonsolidMeat5'),
('NonsolidTwitch'),
('HeadOnAStick'),
('HeadsOnAStick'),
('HeadCandles'),
('DeadStick'),
('LiveStick'),
('BigTree'),
('BurningBarrel'),
('HangNoGuts'),
('HangBNoBrain'),
('HangTLookingDown'),
('HangTLookingUp'),
('HangTSkull'),
('HangTNoBrain'),
('ColonGibs'),
('SmallBloodPool'),
('BrainStem'),
('Stalagmite'),
# actors/doom/doomhealth.txt
('HealthBonus'),
('Stimpack'),
('Medikit'),
# actors/doom/doomimp.txt
('DoomImp'),
('DoomImpBall'),
# actors/doom/doomkeys.txt
('DoomKey'),
('BlueCard'),
('YellowCard'),
('RedCard'),
('BlueSkull'),
('YellowSkull'),
('RedSkull'),
# actors/doom/doommisc.txt
('ExplosiveBarrel'),
('BulletPuff'),
('DoomUnusedStates'),
('EvilSceptre'),
('UnholyBible'),
# actors/doom/doomplayer.txt
('DoomPlayer'),
# actors/doom/doomweapons.txt
('DoomWeapon'),
('Fist'),
('Pistol'),
('Chainsaw'),
('Shotgun'),
('SuperShotgun'),
('Chaingun'),
('RocketLauncher'),
('Rocket'),
('Grenade'),
('PlasmaRifle'),
('PlasmaBall'),
('PlasmaBall1'),
('PlasmaBall2'),
('BFG9000'),
('BFGBall'),
('BFGExtra'),
# actors/doom/fatso.txt
('Fatso'),
('FatShot'),
# actors/doom/keen.txt
('CommanderKeen'),
# actors/doom/lostsoul.txt
('LostSoul'),
('BetaSkull'),
# actors/doom/painelemental.txt
('PainElemental'),
# actors/doom/possessed.txt
('ZombieMan'),
('ShotgunGuy'),
('ChaingunGuy'),
('WolfensteinSS'),
# actors/doom/revenant.txt
('Revenant'),
('RevenantTracer'),
('RevenantTracerSmoke'),
# actors/doom/scriptedmarine.txt
('MarineFist'),
('MarineBerserk'),
('MarineChainsaw'),
('MarinePistol'),
('MarineShotgun'),
('MarineSSG'),
('MarineChaingun'),
('MarineRocket'),
('MarinePlasma'),
('MarineRailgun'),
('MarineBFG'),
# actors/doom/spidermaster.txt
('SpiderMastermind'),
# actors/doom/stealthmonsters.txt
('StealthArachnotron'),
('StealthArchvile'),
('StealthBaron'),
('StealthCacodemon'),
('StealthChaingunGuy'),
('StealthDemon'),
('StealthHellKnight'),
('StealthDoomImp'),
('StealthFatso'),
('StealthRevenant'),
('StealthShotgunGuy'),
('StealthZombieMan'),
# actors/heretic/beast.txt
('Beast'),
('BeastBall'),
('Puffy'),
# actors/heretic/chicken.txt
('BeakPuff'),
('Beak'),
('BeakPowered'),
('Chicken'),
('Feather'),
# actors/heretic/clink.txt
('Clink'),
# actors/heretic/dsparil.txt
('BossSpot'),
('Sorcerer1'),
('SorcererFX1'),
('Sorcerer2'),
('Sorcerer2FX1'),
('Sorcerer2FXSpark'),
('Sorcerer2FX2'),
('Sorcerer2Telefade'),
# actors/heretic/hereticammo.txt
('GoldWandAmmo'),
('GoldWandHefty'),
('CrossbowAmmo'),
('CrossbowHefty'),
('MaceAmmo'),
('MaceHefty'),
('BlasterAmmo'),
('BlasterHefty'),
('SkullRodAmmo'),
('SkullRodHefty'),
('PhoenixRodAmmo'),
('PhoenixRodHefty'),
('BagOfHolding'),
# actors/heretic/hereticarmor.txt
('SilverShield'),
('EnchantedShield'),
# actors/heretic/hereticartifacts.txt
('SuperMap'),
('ArtiInvisibility'),
('ActivatedTimeBomb'),
# actors/heretic/hereticdecorations.txt
('SkullHang70'),
('SkullHang60'),
('SkullHang45'),
('SkullHang35'),
('Chandelier'),
('SerpentTorch'),
('SmallPillar'),
('StalagmiteSmall'),
('StalagmiteLarge'),
('StalactiteSmall'),
('StalactiteLarge'),
('FireBrazier'),
('Barrel'),
('BrownPillar'),
('Moss1'),
('Moss2'),
('WallTorch'),
('HangingCorpse'),
# actors/heretic/hereticimp.txt
('HereticImp'),
('HereticImpLeader'),
('HereticImpChunk1'),
('HereticImpChunk2'),
('HereticImpBall'),
# actors/heretic/heretickeys.txt
('HereticKey'),
('KeyGreen'),
('KeyBlue'),
('KeyYellow'),
('KeyGizmoBlue'),
('KeyGizmoFloatBlue'),
('KeyGizmoGreen'),
('KeyGizmoFloatGreen'),
('KeyGizmoYellow'),
('KeyGizmoFloatYellow'),
# actors/heretic/hereticmisc.txt
('Pod'),
('PodGoo'),
('PodGenerator'),
('TeleGlitterGenerator1'),
('TeleGlitterGenerator2'),
('TeleGlitter1'),
('TeleGlitter2'),
('Volcano'),
('VolcanoBlast'),
('VolcanoTBlast'),
# actors/heretic/hereticplayer.txt
('HereticPlayer'),
('BloodySkull'),
# actors/heretic/hereticweaps.txt
('HereticWeapon'),
('Staff'),
('StaffPowered'),
('StaffPuff'),
('StaffPuff2'),
('GoldWand'),
('GoldWandPowered'),
('GoldWandFX1'),
('GoldWandFX2'),
('GoldWandPuff1'),
('GoldWandPuff2'),
('Crossbow'),
('CrossbowPowered'),
('CrossbowFX1'),
('CrossbowFX2'),
('CrossbowFX3'),
('CrossbowFX4'),
('Gauntlets'),
('GauntletsPowered'),
('GauntletPuff1'),
('GauntletPuff2'),
('Mace'),
('MacePowered'),
('MaceFX1'),
('MaceFX2'),
('MaceFX3'),
('MaceSpawner'),
('Blaster'),
('BlasterPowered'),
('BlasterSmoke'),
('BlasterPuff'),
('SkullRod'),
('SkullRodPowered'),
('HornRodFX1'),
('PhoenixPuff'),
# actors/heretic/ironlich.txt
('Ironlich'),
('HeadFX1'),
('HeadFX2'),
('HeadFX3'),
# actors/heretic/knight.txt
('Knight'),
('KnightGhost'),
('KnightAxe'),
('RedAxe'),
# actors/heretic/mummy.txt
('Mummy'),
('MummyLeader'),
('MummyGhost'),
('MummyLeaderGhost'),
('MummySoul'),
('MummyFX1'),
# actors/heretic/snake.txt
('Snake'),
('SnakeProjA'),
('SnakeProjB'),
# actors/heretic/wizard.txt
('Wizard'),
('WizardFX1'),
# actors/hexen/bats.txt
('BatSpawner'),
('Bat'),
# actors/hexen/bishop.txt
('Bishop'),
('BishopPuff'),
('BishopPainBlur'),
('BishopFX'),
('BishopBlur'),
# actors/hexen/blastradius.txt
('ArtiBlastRadius'),
('BlastEffect'),
# actors/hexen/centaur.txt
('Centaur'),
('CentaurLeader'),
('CentaurMash'),
('CentaurFX'),
('CentaurShield'),
('CentaurSword'),
# actors/hexen/clericboss.txt
('ClericBoss'),
# actors/hexen/clericflame.txt
('CWeapFlame'),
('CFlameFloor'),
('FlamePuff'),
('FlamePuff2'),
('CircleFlame'),
# actors/hexen/clericholy.txt
('ClericWeaponPiece'),
('CWeaponPiece1'),
('CWeaponPiece2'),
('CWeaponPiece3'),
('WraithvergeDrop'),
('HolyMissile'),
('HolyMissilePuff'),
('HolyPuff'),
('HolyTail'),
('HolyTailTrail'),
# actors/hexen/clericmace.txt
('CWeapMace'),
# actors/hexen/clericplayer.txt
('ClericPlayer'),
# actors/hexen/clericstaff.txt
('CWeapStaff'),
('CStaffPuff'),
# actors/hexen/demons.txt
('Demon1'),
('Demon1Mash'),
('DemonChunk'),
('Demon1Chunk1'),
('Demon1Chunk2'),
('Demon1Chunk3'),
('Demon1Chunk4'),
('Demon1Chunk5'),
('Demon1FX1'),
('Demon2'),
('Demon2Mash'),
('Demon2Chunk1'),
('Demon2Chunk2'),
('Demon2Chunk3'),
('Demon2Chunk4'),
('Demon2Chunk5'),
('Demon2FX1'),
# actors/hexen/dragon.txt
('Dragon'),
('DragonFireball'),
('DragonExplosion'),
# actors/hexen/ettin.txt
('Ettin'),
('EttinMace'),
('EttinMash'),
# actors/hexen/fighteraxe.txt
('AxePuff'),
('AxePuffGlow'),
# actors/hexen/fighterboss.txt
('FighterBoss'),
# actors/hexen/fighterfist.txt
('FWeapFist'),
('PunchPuff'),
# actors/hexen/fighterhammer.txt
('FWeapHammer'),
('HammerMissile'),
('HammerPuff'),
# actors/hexen/fighterplayer.txt
('FighterPlayer'),
('BloodyFighterSkull'),
# actors/hexen/fighterquietus.txt
('FighterWeaponPiece'),
('FWeaponPiece1'),
('FWeaponPiece2'),
('FWeaponPiece3'),
('QuietusDrop'),
('FWeapQuietus'),
('FSwordFlame'),
# actors/hexen/firedemon.txt
('FireDemon'),
('FireDemonSplotch1'),
('FireDemonSplotch2'),
('FireDemonRock1'),
('FireDemonRock2'),
('FireDemonRock3'),
('FireDemonRock4'),
('FireDemonRock5'),
('FireDemonMissile'),
# actors/hexen/flame.txt
('FlameSmallTemp'),
('FlameLargeTemp'),
('FlameSmall'),
('FlameSmall2'),
('FlameLarge'),
('FlameLarge2'),
# actors/hexen/flechette.txt
('PoisonBag'),
('FireBomb'),
('ThrowingBomb'),
('ZPoisonShroom'),
# actors/hexen/fog.txt
('FogSpawner'),
('FogPatchSmall'),
('FogPatchMedium'),
('FogPatchLarge'),
# actors/hexen/heresiarch.txt
('SorcFX1'),
('SorcFX2'),
('SorcFX2T1'),
('SorcFX3'),
('SorcFX3Explosion'),
('SorcFX4'),
('SorcSpark1'),
# actors/hexen/hexenarmor.txt
('MeshArmor'),
('FalconShield'),
('PlatinumHelm'),
('AmuletOfWarding'),
# actors/hexen/hexendecorations.txt
('ZWingedStatue'),
('ZRock1'),
('ZRock2'),
('ZRock3'),
('ZRock4'),
('ZChandelier'),
('ZChandelierUnlit'),
('ZTreeDead'),
('ZTree'),
('ZTreeSwamp150'),
('ZTreeSwamp120'),
('ZStumpBurned'),
('ZStumpBare'),
('ZStumpSwamp1'),
('ZStumpSwamp2'),
('ZShroomLarge1'),
('ZShroomLarge2'),
('ZShroomLarge3'),
('ZShroomSmall1'),
('ZShroomSmall2'),
('ZShroomSmall3'),
('ZShroomSmall4'),
('ZShroomSmall5'),
('ZStalagmitePillar'),
('ZStalagmiteLarge'),
('ZStalagmiteMedium'),
('ZStalagmiteSmall'),
('ZStalactiteLarge'),
('ZStalactiteMedium'),
('ZStalactiteSmall'),
('ZMossCeiling1'),
('ZMossCeiling2'),
('ZSwampVine'),
('ZCorpseKabob'),
('ZCorpseSleeping'),
('ZTombstoneRIP'),
('ZTombstoneShane'),
('ZTombstoneBigCross'),
('ZTombstoneBrianR'),
('ZTombstoneCrossCircle'),
('ZTombstoneSmallCross'),
('ZTombstoneBrianP'),
('ZCorpseHanging'),
('ZStatueGargoyleGreenTall'),
('ZStatueGargoyleBlueTall'),
('ZStatueGargoyleGreenShort'),
('ZStatueGargoyleBlueShort'),
('ZStatueGargoyleStripeTall'),
('ZStatueGargoyleDarkRedTall'),
('ZStatueGargoyleRedTall'),
('ZStatueGargoyleTanTall'),
('ZStatueGargoyleRustTall'),
('ZStatueGargoyleDarkRedShort'),
('ZStatueGargoyleRedShort'),
('ZStatueGargoyleTanShort'),
('ZStatueGargoyleRustShort'),
('ZBannerTattered'),
('ZTreeLarge1'),
('ZTreeLarge2'),
('ZTreeGnarled1'),
('ZTreeGnarled2'),
('ZLog'),
('ZStalactiteIceLarge'),
('ZStalactiteIceMedium'),
('ZStalactiteIceSmall'),
('ZStalactiteIceTiny'),
('ZStalagmiteIceLarge'),
('ZStalagmiteIceMedium'),
('ZStalagmiteIceSmall'),
('ZStalagmiteIceTiny'),
('ZRockBrown1'),
('ZRockBrown2'),
('ZRockBlack'),
('ZRubble1'),
('ZRubble2'),
('ZRubble3'),
('ZVasePillar'),
('ZCorpseLynched'),
('ZCandle'),
('ZBarrel'),
('ZBucket'),
('FireThing'),
('BrassTorch'),
('ZBlueCandle'),
('ZIronMaiden'),
('ZChainBit32'),
('ZChainBit64'),
('ZChainEndHeart'),
('ZChainEndHook1'),
('ZChainEndHook2'),
('ZChainEndSpike'),
('ZChainEndSkull'),
('TableShit1'),
('TableShit2'),
('TableShit3'),
('TableShit4'),
('TableShit5'),
('TableShit6'),
('TableShit7'),
('TableShit8'),
('TableShit9'),
('TableShit10'),
('TeleSmoke'),
# actors/hexen/hexenkeys.txt
('HexenKey'),
('KeySteel'),
('KeyCave'),
('KeyAxe'),
('KeyFire'),
('KeyEmerald'),
('KeyDungeon'),
('KeySilver'),
('KeyRusted'),
('KeyHorn'),
('KeySwamp'),
('KeyCastle'),
# actors/hexen/hexenspecialdecs.txt
('ZWingedStatueNoSkull'),
('ZGemPedestal'),
('TreeDestructible'),
('Pottery2'),
('Pottery3'),
('PotteryBit'),
('BloodPool'),
('CorpseBloodDrip'),
('CorpseBit'),
('ZCorpseSitting'),
('LeafSpawner'),
('Leaf1'),
('Leaf2'),
('ZTwinedTorch'),
('ZTwinedTorchUnlit'),
('ZWallTorch'),
('ZWallTorchUnlit'),
('ZShrub1'),
('ZShrub2'),
('ZFireBull'),
('ZFireBullUnlit'),
('ZSuitOfArmor'),
('ZArmorChunk'),
('ZXmasTree'),
('ZCauldron'),
('ZCauldronUnlit'),
('HWaterDrip'),
# actors/hexen/iceguy.txt
('IceGuy'),
('IceGuyFX'),
('IceFXPuff'),
('IceGuyFX2'),
('IceGuyBit'),
('IceGuyWisp1'),
('IceGuyWisp2'),
# actors/hexen/korax.txt
('Korax'),
('KoraxSpirit'),
('KoraxBolt'),
# actors/hexen/mageboss.txt
('MageBoss'),
# actors/hexen/magecone.txt
('MWeapFrost'),
('IceShard'),
# actors/hexen/magelightning.txt
('MWeapLightning'),
('LightningCeiling'),
('LightningFloor'),
# actors/hexen/mageplayer.txt
('MagePlayer'),
# actors/hexen/magestaff.txt
('MageWeaponPiece'),
('MWeaponPiece1'),
('MWeaponPiece2'),
('MWeaponPiece3'),
('BloodscourgeDrop'),
# actors/hexen/magewand.txt
('MWeapWand'),
('MageWandSmoke'),
('MageWandMissile'),
# actors/hexen/mana.txt
('Mana1'),
('Mana2'),
('Mana3'),
('ArtiBoostMana'),
# actors/hexen/pig.txt
('SnoutPuff'),
('Snout'),
('Pig'),
# actors/hexen/puzzleitems.txt
('PuzzSkull'),
('PuzzGemBig'),
('PuzzGemRed'),
('PuzzGemGreen1'),
('PuzzGemGreen2'),
('PuzzGemBlue1'),
('PuzzGemBlue2'),
('PuzzBook1'),
('PuzzBook2'),
('PuzzFlameMask'),
('PuzzFWeapon'),
('PuzzCWeapon'),
('PuzzMWeapon'),
('PuzzGear1'),
('PuzzGear2'),
('PuzzGear3'),
('PuzzGear4'),
# actors/hexen/scriptprojectiles.txt
('FireBall'),
('Arrow'),
('Dart'),
('PoisonDart'),
('RipperBall'),
('ProjectileBlade'),
# actors/hexen/serpent.txt
('Serpent'),
('SerpentLeader'),
('SerpentFX'),
('SerpentHead'),
('SerpentGib1'),
('SerpentGib2'),
('SerpentGib3'),
# actors/hexen/speedboots.txt
('ArtiSpeedBoots'),
# actors/hexen/spike.txt
('DirtClump'),
('ThrustFloorUp'),
('ThrustFloorDown'),
# actors/hexen/summon.txt
('SummoningDoll'),
('MinotaurSmoke'),
# actors/hexen/teleportother.txt
('TelOtherFX2'),
('TelOtherFX3'),
('TelOtherFX4'),
('TelOtherFX5'),
# actors/hexen/wraith.txt
('Wraith'),
('WraithBuried'),
('WraithFX1'),
('WraithFX2'),
('WraithFX3'),
('WraithFX4'),
('WraithFX5'),
# actors/raven/artiegg.txt
('EggFX'),
('ArtiEgg'),
('PorkFX'),
('ArtiPork'),
# actors/raven/minotaur.txt
('MinotaurFX1'),
('MinotaurFX2'),
('MinotaurFX3'),
('MinotaurSmokeExit'),
# actors/raven/ravenambient.txt
('SoundWind'),
('SoundWindHexen'),
('SoundWaterfall'),
# actors/raven/ravenartifacts.txt
('ArtiHealth'),
('ArtiSuperHealth'),
('ArtiFly'),
('ArtiInvulnerability'),
('ArtiInvulnerability2'),
('ArtiTorch'),
# actors/raven/ravenhealth.txt
('CrystalVial'),
# actors/shared/action.txt
('IceChunk'),
('IceChunkHead'),
# actors/shared/blood.txt
('Blood'),
('BloodSplatter'),
('AxeBlood'),
# actors/shared/botstuff.txt
('CajunBodyNode'),
('CajunTrace'),
# actors/shared/bridge.txt
('BridgeBall'),
('Bridge'),
('ZBridge'),
('InvisibleBridge32'),
('InvisibleBridge16'),
('InvisibleBridge8'),
# actors/shared/camera.txt
('DoomBuilderCamera'),
# actors/shared/debris.txt
('Rock1'),
('Rock2'),
('Rock3'),
('Dirt1'),
('Dirt2'),
('Dirt3'),
('Dirt4'),
('Dirt5'),
('Dirt6'),
('SGShard1'),
('SGShard2'),
('SGShard3'),
('SGShard4'),
('SGShard5'),
('SGShard6'),
('SGShard7'),
('SGShard8'),
('SGShard9'),
('SGShard0'),
('GlassJunk'),
# actors/shared/dog.txt
('MBFHelperDog'),
# actors/shared/fountain.txt
('RedParticleFountain'),
('GreenParticleFountain'),
('BlueParticleFountain'),
('YellowParticleFountain'),
('PurpleParticleFountain'),
('BlackParticleFountain'),
('WhiteParticleFountain'),
# actors/shared/inventory.txt
('PowerGhost'),
('PowerShadow'),
# actors/shared/pickups.txt
('ItemFog'),
('PickupFlash'),
# actors/shared/player.txt
('native'),
# actors/shared/sharedmisc.txt
('Unknown'),
('PatrolPoint'),
('PatrolSpecial'),
('MapSpot'),
('FS_Mapspot'),
('MapSpotGravity'),
('PointPusher'),
('PointPuller'),
('RealGibs'),
('Gibs'),
('SpeakerIcon'),
# actors/shared/skies.txt
('UpperStackLookOnly'),
('LowerStackLookOnly'),
# actors/shared/soundsequence.txt
('AmbientSoundNoGravity'),
('HereticSoundSequence1'),
('HereticSoundSequence2'),
('HereticSoundSequence3'),
('HereticSoundSequence4'),
('HereticSoundSequence5'),
('HereticSoundSequence6'),
('HereticSoundSequence7'),
('HereticSoundSequence8'),
('HereticSoundSequence9'),
('HereticSoundSequence10'),
# actors/shared/splashes.txt
('WaterSplash'),
('WaterSplashBase'),
('LavaSplash'),
('LavaSmoke'),
('SludgeChunk'),
('SludgeSplash'),
('BloodSplash'),
('BloodSplashBase'),
('SlimeChunk'),
('SlimeSplash'),
('RocketSmokeTrail'),
('GrenadeSmokeTrail'),
# actors/shared/teleport.txt
('TeleportDest'),
('TeleportDest2'),
('TeleportDest3'),
# actors/strife/acolyte.txt
('Acolyte'),
('AcolyteTan'),
('AcolyteRed'),
('AcolyteRust'),
('AcolyteGray'),
('AcolyteDGreen'),
('AcolyteGold'),
('AcolyteLGreen'),
('AcolyteBlue'),
('AcolyteShadow'),
('AcolyteToBe'),
# actors/strife/alienspectres.txt
('AlienSpectre1'),
('AlienSpectre2'),
('AlienSpectre3'),
('AlienSpectre4'),
('AlienSpectre5'),
('AlienChunkSmall'),
('AlienChunkLarge'),
# actors/strife/beggars.txt
('Beggar'),
('Beggar1'),
('Beggar2'),
('Beggar3'),
('Beggar4'),
('Beggar5'),
# actors/strife/coin.txt
('Gold10'),
('Gold25'),
('Gold50'),
('Gold300'),
# actors/strife/crusader.txt
('Crusader'),
('FastFlameMissile'),
('CrusaderMissile'),
('DeadCrusader'),
# actors/strife/entityboss.txt
('EntityNest'),
('EntityPod'),
('EntityBoss'),
('EntitySecond'),
# actors/strife/inquisitor.txt
('Inquisitor'),
('InquisitorShot'),
('InquisitorArm'),
# actors/strife/loremaster.txt
('Loremaster'),
('LoreShot2'),
# actors/strife/macil.txt
('Macil1'),
('Macil2'),
# actors/strife/merchants.txt
('Merchant'),
('WeaponSmith'),
('BarKeep'),
('Armorer'),
('Medic'),
# actors/strife/oracle.txt
('Oracle'),
# actors/strife/peasants.txt
('Peasant'),
('Peasant1'),
('Peasant2'),
('Peasant3'),
('Peasant4'),
('Peasant5'),
('Peasant6'),
('Peasant7'),
('Peasant8'),
('Peasant9'),
('Peasant10'),
('Peasant11'),
('Peasant12'),
('Peasant13'),
('Peasant14'),
('Peasant15'),
('Peasant16'),
('Peasant17'),
('Peasant18'),
('Peasant19'),
('Peasant20'),
('Peasant21'),
('Peasant22'),
# actors/strife/programmer.txt
('Programmer'),
('ProgrammerBase'),
# actors/strife/questitems.txt
('QuestItem'),
('QuestItem1'),
('QuestItem2'),
('QuestItem3'),
('QuestItem4'),
('QuestItem5'),
('QuestItem6'),
('QuestItem7'),
('QuestItem8'),
('QuestItem9'),
('QuestItem10'),
('QuestItem11'),
('QuestItem12'),
('QuestItem13'),
('QuestItem14'),
('QuestItem15'),
('QuestItem16'),
('QuestItem17'),
('QuestItem18'),
('QuestItem19'),
('QuestItem20'),
('QuestItem21'),
('QuestItem22'),
('QuestItem23'),
('QuestItem24'),
('QuestItem25'),
('QuestItem26'),
('QuestItem27'),
('QuestItem28'),
('QuestItem29'),
('QuestItem30'),
('QuestItem31'),
# actors/strife/ratbuddy.txt
('RatBuddy'),
# actors/strife/reaver.txt
('Reaver'),
# actors/strife/rebels.txt
('Rebel'),
('Rebel1'),
('Rebel2'),
('Rebel3'),
('Rebel4'),
('Rebel5'),
('Rebel6'),
# actors/strife/sentinel.txt
('Sentinel'),
('SentinelFX1'),
('SentinelFX2'),
# actors/strife/sigil.txt
('Sigil1'),
('Sigil2'),
('Sigil3'),
('Sigil4'),
('Sigil5'),
# actors/strife/spectral.txt
('SpectralLightningBase'),
('SpectralLightningDeath1'),
('SpectralLightningDeath2'),
('SpectralLightningDeathShort'),
('SpectralLightningBall1'),
('SpectralLightningBall2'),
('SpectralLightningH1'),
('SpectralLightningH2'),
('SpectralLightningH3'),
('SpectralLightningHTail'),
('SpectralLightningBigBall1'),
('SpectralLightningBigBall2'),
('SpectralLightningV1'),
('SpectralLightningV2'),
('SpectralLightningSpot'),
('SpectralLightningBigV1'),
('SpectralLightningBigV2'),
# actors/strife/stalker.txt
('Stalker'),
# actors/strife/strifeammo.txt
('HEGrenadeRounds'),
('PhosphorusGrenadeRounds'),
('ClipOfBullets'),
('BoxOfBullets'),
('MiniMissiles'),
('CrateOfMissiles'),
('EnergyPod'),
('EnergyPack'),
('PoisonBolts'),
('ElectricBolts'),
('AmmoSatchel'),
# actors/strife/strifearmor.txt
('MetalArmor'),
('LeatherArmor'),
# actors/strife/strifebishop.txt
('StrifeBishop'),
('BishopMissile'),
# actors/strife/strifehumanoid.txt
('StrifeHumanoid'),
('FireDroplet'),
# actors/strife/strifeitems.txt
('MedPatch'),
('MedicalKit'),
('SurgeryKit'),
('StrifeMap'),
('BeldinsRing'),
('OfferingChalice'),
('Ear'),
('BrokenPowerCoupling'),
('ShadowArmor'),
('EnvironmentalSuit'),
('GuardUniform'),
('OfficersUniform'),
('FlameThrowerParts'),
('InterrogatorReport'),
('Info'),
('Targeter'),
('Communicator'),
('GunTraining'),
# actors/strife/strifekeys.txt
('StrifeKey'),
('BaseKey'),
('GovsKey'),
('Passcard'),
('IDBadge'),
('PrisonKey'),
('SeveredHand'),
('Power1Key'),
('Power2Key'),
('Power3Key'),
('GoldKey'),
('IDCard'),
('SilverKey'),
('OracleKey'),
('MilitaryID'),
('OrderKey'),
('WarehouseKey'),
('BrassKey'),
('RedCrystalKey'),
('BlueCrystalKey'),
('ChapelKey'),
('CatacombKey'),
('SecurityKey'),
('CoreKey'),
('MaulerKey'),
('FactoryKey'),
('MineKey'),
('NewKey5'),
('OraclePass'),
# actors/strife/strifeplayer.txt
('StrifePlayer'),
# actors/strife/strifestuff.txt
('Tank1'),
('Tank2'),
('Tank3'),
('Tank4'),
('Tank5'),
('Tank6'),
('WaterBottle'),
('Mug'),
('WoodenBarrel'),
('ExplosiveBarrel2'),
('LightSilverFluorescent'),
('LightBrownFluorescent'),
('LightGoldFluorescent'),
('LightGlobe'),
('PillarTechno'),
('PillarAztec'),
('PillarAztecDamaged'),
('PillarAztecRuined'),
('PillarHugeTech'),
('PillarAlienPower'),
('SStalactiteBig'),
('SStalactiteSmall'),
('SStalagmiteBig'),
('CavePillarTop'),
('CavePillarBottom'),
('SStalagmiteSmall'),
('Candle'),
('StrifeCandelabra'),
('WaterDropOnFloor'),
('WaterfallSplash'),
('WaterDrip'),
('WaterFountain'),
('HeartsInTank'),
('TeleportSwirl'),
('DeadStrifePlayer'),
('DeadPeasant'),
('DeadAcolyte'),
('DeadReaver'),
('DeadRebel'),
('SacrificedGuy'),
('PileOfGuts'),
('StrifeBurningBarrel'),
('BurningBowl'),
('BurningBrazier'),
('SmallTorchLit'),
('SmallTorchUnlit'),
('CeilingChain'),
('CageLight'),
('Statue'),
('StatueRuined'),
('MediumTorch'),
('OutsideLamp'),
('PoleLantern'),
('SRock1'),
('SRock2'),
('SRock3'),
('SRock4'),
('StickInWater'),
('Rubble1'),
('Rubble2'),
('Rubble3'),
('Rubble4'),
('Rubble5'),
('Rubble6'),
('Rubble7'),
('Rubble8'),
('SurgeryCrab'),
('LargeTorch'),
('HugeTorch'),
('PalmTree'),
('BigTree2'),
('PottedTree'),
('TreeStub'),
('ShortBush'),
('TallBush'),
('ChimneyStack'),
('BarricadeColumn'),
('Pot'),
('Pitcher'),
('Stool'),
('MetalPot'),
('Tub'),
('Anvil'),
('TechLampSilver'),
('TechLampBrass'),
('Tray'),
('AmmoFiller'),
('SigilBanner'),
('RebelBoots'),
('RebelHelmet'),
('RebelShirt'),
('AlienBubbleColumn'),
('AlienFloorBubble'),
('AlienCeilingBubble'),
('AlienAspClimber'),
('AlienSpiderLight'),
('TargetPractice'),
('KneelingGuy'),
('KlaxonWarningLight'),
('CeilingTurret'),
('Junk'),
# actors/strife/strifeweapons.txt
('StrifeWeapon'),
('StrifePuff'),
('StrifeSpark'),
('PunchDagger'),
('StrifeZap1'),
('ElectricBolt'),
('StrifeCrossbow'),
('StrifeCrossbow2'),
('AssaultGun'),
('AssaultGunStanding'),
('MiniMissileLauncher'),
('RocketTrail'),
('MiniMissilePuff'),
('MiniMissile'),
('FlameThrower'),
('FlameMissile'),
('Mauler'),
('Mauler2'),
('MaulerPuff'),
('MaulerTorpedo'),
('MaulerTorpedoWave'),
('HEGrenade'),
('PhosphorousGrenade'),
('StrifeGrenadeLauncher'),
('StrifeGrenadeLauncher2'),
# actors/strife/templar.txt
('Templar'),
# actors/strife/thingstoblowup.txt
('Bang4Cloud'),
('Piston'),
('Computer'),
('PowerCrystal'),
# actors/strife/zombie.txt
('Zombie'),
('ZombieSpawner'),
)
